package:
  name: lightning
  version: "0.2.dev0"

source:
  git_url: https://github.com/scikit-learn-contrib/lightning.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
  run:
    - python

test:
  requires:
    - numpy
    - scikit-learn
    - nose
  imports:
    - lightning

about:
  home: http://contrib.scikit-learn.org/lightning/
  license: BSD
